name: "sticky-thumbnailer"
listen: ":8080"
db: /data/overseer.db

task_pool:
  limit: 2
  queue:
    enabled: true
    size: 200

actions:
  thumbnail:
    type: thumbnailer
    dedupe_key: ["file"]
    config:
      scan_interval: "5s"
      paths:
        - "/recordings/**/*.ts"
        - "/recordings/**/*.mp4"
      db_path: "/data/thumbnailer.db"
      thumb_levels: 2
